"""
Synthetic lunar-like sample data generator.

IMPORTANT: These images are NOT Chandrayaan-2 imagery. They are procedurally
generated grayscale textures that mimic the *visual character* of lunar
surface images (craters, regolith texture, albedo variation) purely so the
MoonMatrix AI prototype has something to run on out-of-the-box.

See DATA_GUIDE.md for instructions on replacing these with real Chandrayaan-2
OHRC / TMC-2 / IIRS data (from ISRO's Pradan portal).
"""
from __future__ import annotations

import os
import numpy as np
import cv2

RNG_SEED = 42


def _draw_crater(img: np.ndarray, cx: int, cy: int, r: int, rng: np.random.Generator) -> None:
    """Paint one crater (dark rim shadow + bright far rim + dark floor) onto img (float32, 0-1)."""
    h, w = img.shape
    yy, xx = np.ogrid[:h, :w]
    dist = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)

    floor = np.clip(1.0 - dist / (r * 0.75), 0, 1)
    img -= 0.35 * floor * (dist < r * 0.85)

    rim_band = np.exp(-((dist - r) ** 2) / (2 * (r * 0.12 + 1) ** 2))
    # simple fixed-direction "sun" shading so rims look 3D
    shade = 0.25 * rim_band
    img += shade

    # small random asymmetric highlight to fake a consistent sun angle
    highlight_mask = (xx - cx) < 0
    img += 0.15 * rim_band * highlight_mask
    img -= 0.10 * rim_band * (~highlight_mask)


def generate_lunar_like_image(size=(768, 768), n_craters=55, seed=RNG_SEED) -> np.ndarray:
    """Generate a single synthetic lunar-like grayscale base image, uint8."""
    rng = np.random.default_rng(seed)
    h, w = size
    img = np.full((h, w), 0.5, dtype=np.float32)

    # base regolith texture: layered noise
    for octave, weight in [(4, 0.02), (8, 0.015), (16, 0.01), (32, 0.008)]:
        noise = rng.normal(0, 1, size=(octave, octave)).astype(np.float32)
        noise = cv2.resize(noise, (w, h), interpolation=cv2.INTER_CUBIC)
        img += weight * noise / (noise.std() + 1e-6)

    radii = rng.integers(8, 60, size=n_craters)
    order = np.argsort(-radii)  # biggest craters first, smaller ones drawn on top
    for idx in order:
        r = int(radii[idx])
        cx = int(rng.integers(r, w - r))
        cy = int(rng.integers(r, h - r))
        _draw_crater(img, cx, cy, r, rng)

    img = np.clip(img, 0, 1)
    return (img * 255).astype(np.uint8)


def make_reference_and_source(
    size=(768, 768),
    scale=1.0,
    rotation_deg=8.0,
    tx=25.0,
    ty=-15.0,
    brightness_delta=0,
    contrast_gamma=1.0,
    seed=RNG_SEED,
):
    """
    Build a (reference, source, ground_truth_homography) triple.

    `source` is generated by applying a KNOWN affine/homography-like transform
    (rotation + translation + scale) plus optional illumination change to
    `reference`. This lets the evaluation module report a genuine geometric
    registration error against ground truth, instead of a fabricated number.
    """
    reference = generate_lunar_like_image(size=size, seed=seed)
    h, w = reference.shape

    center = (w / 2, h / 2)
    M = cv2.getRotationMatrix2D(center, rotation_deg, scale)
    M[0, 2] += tx
    M[1, 2] += ty

    source = cv2.warpAffine(
        reference, M, (w, h), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT
    )

    if brightness_delta != 0 or contrast_gamma != 1.0:
        source = apply_illumination(source, brightness_delta, contrast_gamma)

    # 2x3 affine -> 3x3 homography (ground truth: reference -> source)
    H_gt = np.vstack([M, [0, 0, 1]]).astype(np.float64)

    return reference, source, H_gt


def apply_illumination(img: np.ndarray, brightness_delta=0, gamma=1.0) -> np.ndarray:
    """Simulated brightness/contrast/gamma change. NOT a physical sun-angle model."""
    out = img.astype(np.float32)
    out = out + brightness_delta
    out = np.clip(out, 0, 255) / 255.0
    out = np.power(out, gamma)
    return np.clip(out * 255, 0, 255).astype(np.uint8)


def ensure_sample_data(samples_dir: str) -> dict:
    """Create demo sample images on disk if they don't already exist. Returns file paths."""
    os.makedirs(samples_dir, exist_ok=True)
    ref_path = os.path.join(samples_dir, "demo_reference.png")
    src_path = os.path.join(samples_dir, "demo_source.png")

    if not (os.path.exists(ref_path) and os.path.exists(src_path)):
        reference, source, H_gt = make_reference_and_source()
        cv2.imwrite(ref_path, reference)
        cv2.imwrite(src_path, source)
        np.save(os.path.join(samples_dir, "demo_ground_truth_H.npy"), H_gt)

    return {"reference": ref_path, "source": src_path}
